network_type = "lokr"
network_dim = 16
network_alpha = 8
conv_dim = 1
conv_alpha = 4
lokr_factor = 8
decompose_both = true
use_tucker = true
scale_weight_norms = 1.0

learning_rate = 0.0004
lr_scheduler = "cosine"
max_train_epochs = 10
stop_epoch = 6
optimizer_type = "CAME"

output_name = "anima_lokr"

[[datasets]]
validation_split_num = 0

[[datasets.subsets]]
image_dir = "${preprocess_s1.dataset_dir}/hanechan/.resized"
cache_dir = "${preprocess_s1.dataset_dir}/hanechan/.lora"
num_repeats = 1
recursive = true
