"""Trimmed extract of scripts/daemon/proc.py for the vendored daemon client.

Contains only ``read_pidfile`` — the single symbol ``client.py`` touches at
runtime (via ``_resolve_port``). The full live module routes spawn / kill /
liveness through psutil; none of that is needed by the trainer node, which
never auto-starts the daemon (it errors if the daemon isn't already up).
Dropping the psutil import keeps the vendored client pure-stdlib.

DO NOT EDIT — regenerated by scripts/sync_vendor.py.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional


def read_pidfile(path: Path) -> Optional[dict]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
