"""Anima DirectEdit node.

Image in, edited LATENT out. Consumes ComfyUI's stock ``MODEL`` / ``CLIP`` /
``VAE`` sockets - pipe in the same loaders you'd use for a normal Anima
KSampler workflow (``UNETLoader``/``CLIPLoader``/``VAELoader`` or
``CheckpointLoaderSimple``). Both ``source_tag`` and ``target_tag`` are
plain STRING inputs — any node that emits STRING can drive them. Empty
``target_tag`` -> reconstruction sanity-check (target = source).

Pipeline mirrors ``scripts/edit.py``:

  IMAGE -> PIL                        (ComfyUI [B,H,W,C] in [0,1] -> PIL.RGB)
  psi_src = source_tag                (caller-supplied string)
  psi_tar = target_tag or psi_src     (empty target_tag -> reconstruction)
  resize to native res (snapped to 16px grid, capped by max_megapixels)
  CLIP.tokenize / encode_from_tokens(return_dict=True) for psi_src/tar/neg
  diffusion_model.preprocess_text_embeds -> 512-padded crossattn embeds
  VAE.encode + process_latent_in       -> standardized z_clean (DiT input space)
  invert(z_clean, embed_src)           -> z_inv, delta_z
  edit_forward(z_inv[0], delta_z, ...) -> z_edit (still standardized)
  process_latent_out                   -> raw VAE-space LATENT (comfy convention)
"""

from __future__ import annotations

import importlib
import logging
import sys
from pathlib import Path
from typing import Tuple

import numpy as np
import torch

# Resolve where to import ``library.*`` from.
#
# Two install shapes are supported:
#
# 1. **Inside the anima_lora repo** (dev / monorepo install). This file lives
#    at ``anima_lora/custom_nodes/comfyui-anima-directedit/nodes.py`` so
#    ``parents[1]`` of HERE is the repo root, and the live ``library/`` is
#    reachable.
# 2. **Standalone ComfyUI install** (just dropped this folder into
#    ``ComfyUI/custom_nodes/``). Then ``parents[1]`` is ``ComfyUI/custom_nodes/``
#    which has no ``library/`` - fall back to the bundled inference subset
#    under ``_vendor/``. The vendor tree is generated by
#    ``scripts/sync_vendor.py`` in the parent repo and ships with the
#    published node version.
HERE = Path(__file__).resolve().parent
ANIMA_LORA = HERE.parents[1]
VENDOR = HERE / "_vendor"


def _resolve_anima_modules():
    """Return the live ``library`` modules if reachable, else the bundled
    vendor copies. Vendor wins only when the live import fails - in-repo
    edits to ``library/...`` are picked up automatically during development."""
    if str(ANIMA_LORA) not in sys.path:
        sys.path.insert(0, str(ANIMA_LORA))

    def _imports():
        directedit_mod = importlib.import_module("library.inference.editing.directedit")
        sampling_mod = importlib.import_module("library.inference.sampling")
        splice_mod = importlib.import_module(
            "library.inference.editing.directedit_splice"
        )
        return (directedit_mod, sampling_mod, splice_mod)

    try:
        return _imports()
    except ImportError:
        if not VENDOR.exists():
            raise
        if str(VENDOR) not in sys.path:
            sys.path.insert(0, str(VENDOR))
        # Drop any partially-imported modules so the vendor tree's copies
        # actually load (the live attempt may have cached half a tree).
        for k in [
            k
            for k in list(sys.modules)
            if k.startswith(("library.", "networks.")) or k in ("library", "networks")
        ]:
            del sys.modules[k]
        return _imports()


from PIL import Image  # noqa: E402

import comfy.model_management  # noqa: E402  ComfyUI module; only resolvable inside ComfyUI
import comfy.utils  # noqa: E402  ComfyUI module; only resolvable inside ComfyUI

(
    directedit,
    inference_utils,
    _splice_mod,
) = _resolve_anima_modules()
splice_crossattn_emb = _splice_mod.splice_crossattn_emb

# DiT pixel grid: VAE downscale (/8) × patch (/2) = 16px per latent-patch axis.
# Every valid Anima resolution is a multiple of this on both axes.
_DIT_GRID = 16
# Rope per-axis cap is 256 patches = 256 * 16 = 4096px on either axis.
_MAX_AXIS = 4096

# T5 (T5xxl) PAD token id is 0 across the T5 family; vendor doesn't bundle the
# T5 tokenizer config so we hardcode rather than `load_t5_tokenizer().pad_token_id`.
_T5_PAD_ID = 0

logger = logging.getLogger(__name__)


def _snap_axis(n: int) -> int:
    """Snap one axis down to the DiT 16px grid, clamped to [16, 4096px]."""
    return max(_DIT_GRID, min(_MAX_AXIS, n - n % _DIT_GRID))


def _edit_size(pil_img: Image.Image, max_megapixels: float) -> Tuple[int, int]:
    """Target edit resolution from the source's native size. Returns (W, H).

    Uses the image's own resolution and aspect ratio (no aspect-snapping to a
    fixed bucket table). If ``max_megapixels > 0`` and the source exceeds that
    pixel budget, it is scaled down (aspect preserved) to fit; smaller images
    are never upscaled. Both axes are then snapped to the DiT's 16px grid and
    capped at the rope per-axis limit (4096px).
    """
    w, h = pil_img.size
    if max_megapixels and max_megapixels > 0:
        budget = max_megapixels * 1_000_000
        if w * h > budget:
            scale = (budget / (w * h)) ** 0.5
            w = max(1, round(w * scale))
            h = max(1, round(h * scale))
    return _snap_axis(w), _snap_axis(h)


def _comfy_image_to_pil(image_tensor: torch.Tensor) -> Image.Image:
    """ComfyUI IMAGE [B, H, W, C] in [0,1] -> PIL.RGB (first batch element)."""
    arr = image_tensor[0].clamp(0, 1).cpu().numpy()
    return Image.fromarray((arr * 255).astype(np.uint8)).convert("RGB")


def _pil_to_comfy_image(pil_img: Image.Image) -> torch.Tensor:
    """PIL.RGB -> ComfyUI IMAGE [1, H, W, 3] in [0,1] (for VAE.encode input)."""
    arr = np.asarray(pil_img.convert("RGB"), dtype=np.float32) / 255.0
    return torch.from_numpy(arr).unsqueeze(0)


def _norm_tag(tag: str) -> str:
    """Canonical key for tag matching (case/underscore/whitespace-insensitive)."""
    return " ".join(tag.strip().lower().replace("_", " ").split())


def _split_tags(text: str) -> list[str]:
    """Comma-separated tag string -> stripped, non-empty tag list."""
    return [t.strip() for t in (text or "").split(",") if t.strip()]


def _merge_tags(source_caption: str, tags_to_add: str, tags_to_remove: str) -> str:
    """Build the target caption from an auto-derived source caption.

    Drops any ``tags_to_remove`` from the source, then appends each
    ``tags_to_add`` entry that isn't already present (dedup by
    :func:`_norm_tag`). Appending keeps the added tags as a contiguous
    suffix, which is exactly the clean diff-span slot-surgery wants.
    """
    remove_keys = {_norm_tag(t) for t in _split_tags(tags_to_remove)}
    kept = [t for t in _split_tags(source_caption) if _norm_tag(t) not in remove_keys]
    present = {_norm_tag(t) for t in kept}
    for t in _split_tags(tags_to_add):
        if _norm_tag(t) not in present:
            kept.append(t)
            present.add(_norm_tag(t))
    return ", ".join(kept)


def _encode_prompt_comfy(
    clip, unet, text: str, device: torch.device, dtype: torch.dtype
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Tokenize + encode + LLMAdapter preprocess via the comfy CLIP socket.

    Mirrors ``model_base.Anima.extra_conds``: tokenize through the comfy
    Anima tokenizer, encode Qwen3 hidden states + collect t5xxl ids/weights,
    then run the DiT's ``preprocess_text_embeds`` (LLMAdapter + 512 pad)
    once. Verified to produce embeddings within numerical noise of the
    library's ``prepare_text_inputs`` for the prompts we feed DirectEdit.

    Returns ``(embed, t5xxl_ids_512)`` — the 512-padded crossattn tensor and
    the 1-D T5 ids right-padded to 512 with the T5 pad id. Both are needed
    for slot-surgery to align span endpoints with crossattn slot indices.
    """
    tokens = clip.tokenize(text)
    out = clip.encode_from_tokens(tokens, return_pooled=False, return_dict=True)
    cond = out["cond"]  # [1, T_q, 1024]
    t5xxl_ids = out["t5xxl_ids"]  # [T_t5]
    t5xxl_weights = out["t5xxl_weights"]  # [T_t5]

    # Mirror model_base.Anima.extra_conds shape conventions.
    t5xxl_ids = t5xxl_ids.unsqueeze(0).to(device)  # [1, T_t5]
    t5xxl_weights = t5xxl_weights.unsqueeze(0).unsqueeze(-1).to(device, dtype=dtype)
    cond = cond.to(device, dtype=dtype)

    embed = unet.preprocess_text_embeds(cond, t5xxl_ids, t5xxl_weights=t5xxl_weights)

    # Pad T5 ids out to embed.shape[1] (512) with the T5 pad id so splice
    # invariants line up — preprocess_text_embeds 0-pads crossattn, we 0-pad
    # the IDs alongside it.
    t_emb = embed.shape[1]
    if t5xxl_ids.shape[1] < t_emb:
        pad_n = t_emb - t5xxl_ids.shape[1]
        t5xxl_ids = torch.nn.functional.pad(t5xxl_ids, (0, pad_n), value=_T5_PAD_ID)
    elif t5xxl_ids.shape[1] > t_emb:
        t5xxl_ids = t5xxl_ids[:, :t_emb]
    return embed, t5xxl_ids


class AnimaDirectEdit:
    """Image + source/target tag strings -> edited image, on stock MODEL/CLIP/VAE sockets."""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "model": ("MODEL", {"tooltip": "Anima DiT (e.g. UNETLoader)."}),
                "clip": (
                    "CLIP",
                    {"tooltip": "Anima CLIP (Qwen3 06B + T5xxl tokenizer)."},
                ),
                "vae": ("VAE", {"tooltip": "Qwen Image VAE."}),
                "image": ("IMAGE",),
                "max_megapixels": (
                    "FLOAT",
                    {
                        "default": 1.0,
                        "min": 0.0,
                        "max": 16.0,
                        "step": 0.1,
                        "tooltip": (
                            "Megapixel budget for the edit resolution. The "
                            "source is edited at its NATIVE resolution and "
                            "aspect ratio (no bucket snapping); if it exceeds "
                            "this many megapixels it is scaled down to fit "
                            "(aspect preserved, never upscaled). Dims are "
                            "snapped to the DiT 16px grid and capped at 4096px "
                            "per axis. 0 = no cap (use native size as-is). "
                            "Default 1.0 (~1024x1024)."
                        ),
                    },
                ),
                "source_tag": (
                    "STRING",
                    {
                        "multiline": True,
                        "default": "",
                        "tooltip": (
                            "psi_src — caption describing the source image. "
                            "Any STRING source works (paste the original "
                            "prompt for an Anima-generated image, pipe in "
                            "a captioner, etc.). Required (empty raises)."
                        ),
                    },
                ),
                "target_tag": (
                    "STRING",
                    {
                        "multiline": True,
                        "default": "",
                        "tooltip": (
                            "psi_tar — caption for the edited image. Empty -> "
                            "target_tag falls back to source_tag (reconstruction "
                            "sanity check; should reproduce the source). "
                            "Typical usage: copy source_tag and add / replace "
                            "/ remove tags to describe the edit."
                        ),
                    },
                ),
                "negative_prompt": (
                    "STRING",
                    {"multiline": True, "default": "worst quality"},
                ),
                "infer_steps": ("INT", {"default": 20, "min": 1, "max": 200}),
                "flow_shift": (
                    "FLOAT",
                    {"default": 1.0, "min": 0.1, "max": 10.0, "step": 0.05},
                ),
                "guidance_scale": (
                    "FLOAT",
                    {
                        "default": 2.0,
                        "min": 1.0,
                        "max": 20.0,
                        "step": 0.1,
                        "tooltip": "CFG scale for the edit (target) pass.",
                    },
                ),
                "invert_guidance": (
                    "FLOAT",
                    {
                        "default": 1.0,
                        "min": 1.0,
                        "max": 20.0,
                        "step": 0.1,
                        "tooltip": (
                            "CFG scale during inversion. Default 1.0 (no CFG); "
                            "raise only if the inverted noise must match a "
                            "high-CFG generation seed."
                        ),
                    },
                ),
                "t_inj": (
                    "INT",
                    {
                        "default": 6,
                        "min": 0,
                        "max": 200,
                        "tooltip": (
                            "Number of early steps to inject src self-attn V "
                            "into the tar pass (paper Eq. 13). 0 = pure "
                            "deltaZ-anchored edit. Typical: t_inj ~ T/10..T/3 "
                            "(e.g. 3..9 at infer_steps=28). Higher = stronger "
                            "source-feature preservation, weaker edit "
                            "leverage. Injects at all DiT blocks except the "
                            "final (SD3.5-style default)."
                        ),
                    },
                ),
            },
            "optional": {
                "use_slot_surgery": (
                    "BOOLEAN",
                    {
                        "default": False,
                        "tooltip": (
                            "Build embed_tar by transplanting only the "
                            "T5-diff-span slots of psi_tar's crossattn_emb "
                            "into psi_src's encoding. Off by default. "
                            "Untouched slots come from psi_src — see "
                            "library/inference/directedit_splice.py."
                        ),
                    },
                ),
            },
        }

    RETURN_TYPES = ("LATENT",)
    RETURN_NAMES = ("latent",)
    FUNCTION = "edit"
    CATEGORY = "anima"
    DESCRIPTION = (
        "DirectEdit (Yang & Ye arXiv:2605.02417) editor for Anima. Takes "
        "explicit source/target caption STRINGs and runs flow inversion + "
        "delta_z-anchored resampling on the MODEL/CLIP/VAE sockets you wire "
        "in. Returns the edited LATENT in the comfy convention (raw VAE "
        "space) - wire it into VAEDecode to render."
    )

    def edit(
        self,
        model,
        clip,
        vae,
        image: torch.Tensor,
        source_tag: str,
        target_tag: str,
        negative_prompt: str,
        infer_steps: int,
        flow_shift: float,
        guidance_scale: float,
        invert_guidance: float,
        max_megapixels: float = 1.0,
        t_inj: int = 0,
        use_slot_surgery: bool = False,
    ):
        device = comfy.model_management.get_torch_device()
        dtype = torch.bfloat16

        pil_src = _comfy_image_to_pil(image)

        psi_src = (source_tag or "").strip()
        if not psi_src:
            raise ValueError(
                "AnimaDirectEdit: `source_tag` is empty. Provide a caption "
                "describing the source image (any STRING source — e.g. paste "
                "the prompt the source was generated with)."
            )
        psi_tar = (target_tag or "").strip() or psi_src
        if psi_tar == psi_src:
            logger.info(
                "DirectEdit: target_tag empty or identical to source_tag — "
                "reconstruction pass (edit should reproduce the source)."
            )
        logger.info("DirectEdit: psi_src = %r", psi_src)
        logger.info("DirectEdit: psi_tar = %r", psi_tar)

        w_pix, h_pix = _edit_size(pil_src, max_megapixels)
        if (w_pix, h_pix) == pil_src.size:
            pil_src_resized = pil_src
        else:
            pil_src_resized = pil_src.resize((w_pix, h_pix), Image.LANCZOS)
        logger.info(
            "DirectEdit: edit res %dx%d (WxH) from native %dx%d (max_megapixels=%.2f)",
            w_pix,
            h_pix,
            pil_src.size[0],
            pil_src.size[1],
            max_megapixels,
        )

        # Bring DiT onto device so preprocess_text_embeds (LLMAdapter) and the
        # invert/edit forwards see resident weights. ComfyUI's patcher owns
        # eviction - we don't move it back.
        comfy.model_management.load_models_gpu([model])
        unet = model.model.diffusion_model

        with torch.no_grad():
            embed_src, t5_ids_src = _encode_prompt_comfy(
                clip,
                unet,
                psi_src,
                device,
                dtype,
            )
            embed_tar, t5_ids_tar = _encode_prompt_comfy(
                clip,
                unet,
                psi_tar,
                device,
                dtype,
            )
            embed_neg, _ = _encode_prompt_comfy(
                clip,
                unet,
                negative_prompt,
                device,
                dtype,
            )

        if use_slot_surgery:
            embed_tar_full = embed_tar
            embed_tar, span = splice_crossattn_emb(
                crossattn_emb_src=embed_src,
                crossattn_emb_tar=embed_tar_full,
                t5_ids_src=t5_ids_src,
                t5_ids_tar=t5_ids_tar,
                pad_id=_T5_PAD_ID,
            )
            logger.info(
                "DirectEdit slot surgery: diff span src[%d:%d] -> tar[%d:%d] "
                "(src_len=%d tar_len=%d suffix_len=%d)",
                span.start,
                span.src_end,
                span.start,
                span.tar_end,
                span.src_len,
                span.tar_len,
                span.suffix_len,
            )

        # Diagnostic: if psi_src and psi_tar collapse to the same embedding, the
        # edit pass will reconstruct the source by design (deltaz anchors + same
        # velocity field == identity). Big abs-mean diff = encoder is doing
        # its job; near-zero = encoder path is the bug.
        with torch.no_grad():
            d_st = (embed_src.float() - embed_tar.float()).abs().mean().item()
            d_sn = (embed_src.float() - embed_neg.float()).abs().mean().item()
            d_tn = (embed_tar.float() - embed_neg.float()).abs().mean().item()
        logger.info(
            "DirectEdit embed diffs (abs mean): "
            "|src-tar|=%.6f  |src-neg|=%.6f  |tar-neg|=%.6f  "
            "(src.norm=%.3f tar.norm=%.3f shape=%s)",
            d_st,
            d_sn,
            d_tn,
            embed_src.float().norm().item(),
            embed_tar.float().norm().item(),
            tuple(embed_src.shape),
        )
        if d_st < 1e-4 and psi_src != psi_tar:
            logger.warning(
                "DirectEdit: |src-tar| < 1e-4 but psi_src != psi_tar — "
                "encoder collapsed two different captions into the same "
                "embedding. Edit pass will reconstruct the source."
            )

        logger.info("DirectEdit: encoding source image via VAE")
        img_in = _pil_to_comfy_image(pil_src_resized)
        z_clean = vae.encode(img_in)  # [1, C_lat, T=1, H/8, W/8]  RAW VAE latent
        # Anima DiT was trained on standardized latents (per-channel (z - mean) / std);
        # comfy's KSampler applies this via samplers.py::process_latent_in, but we call
        # the diffusion_model directly and must do it ourselves. Without this the model
        # sees out-of-distribution inputs and emits ~zero velocity, so the deltaz-anchored
        # Euler step reconstructs the source regardless of t_inj / guidance_scale.
        z_clean = model.model.process_latent_in(z_clean)
        z_clean = z_clean.to(device, dtype=dtype)
        logger.info("DirectEdit: encoded source latent %s", tuple(z_clean.shape))

        _, sigmas = inference_utils.get_timesteps_sigmas(
            infer_steps, flow_shift, device
        )
        sigmas = sigmas.to(device)

        logger.info(
            "DirectEdit: invert (T=%d, src_guidance=%.2f) -> edit "
            "(tar_guidance=%.2f, t_inj=%d)",
            infer_steps,
            invert_guidance,
            guidance_scale,
            t_inj,
        )
        # Two-phase progress bar: invert occupies [0, T), edit occupies [T, 2T).
        pbar = comfy.utils.ProgressBar(infer_steps * 2)
        z_inv, delta_z = directedit.invert(
            anima=unet,
            z_clean=z_clean,
            embed_src=embed_src,
            embed_neg=embed_neg if invert_guidance != 1.0 else None,
            sigmas=sigmas,
            guidance_scale=invert_guidance,
            step_callback=lambda step, total: pbar.update_absolute(step),
        )
        z_edit = directedit.edit_forward(
            anima=unet,
            z_init=z_inv[0],
            delta_z=delta_z,
            embed_tar=embed_tar,
            embed_neg=embed_neg,
            sigmas=sigmas,
            guidance_scale=guidance_scale,
            embed_src=embed_src if t_inj > 0 else None,
            t_inj=t_inj,
            # t_inj_blocks=None -> directedit defaults to all-but-last (SD3.5 style).
            z_inv=z_inv if t_inj > 0 else None,
            step_callback=lambda step, total: pbar.update_absolute(infer_steps + step),
        )

        # Return a LATENT in raw VAE space to match the comfy convention
        # (samplers.py::process_latent_out is the equivalent step in the
        # KSampler pipeline). Wire into VAEDecode to render.
        z_edit_raw = model.model.process_latent_out(z_edit.to(dtype=dtype))
        logger.info("DirectEdit: returning edited latent %s", tuple(z_edit_raw.shape))
        return ({"samples": z_edit_raw.cpu()},)


class AnimaDirectEditAutoTag:
    """DirectEdit with the source caption auto-derived by an AnimaTagger.

    Convenience wrapper around :class:`AnimaDirectEdit`. Instead of hand-writing
    both ``source_tag`` and ``target_tag``, you wire in an ``ANIMA_TAGGER``
    (from ``Anima Tagger Loader``) and describe the edit as a small delta:

      psi_src = tagger.predict_caption(image)        (auto)
      psi_tar = psi_src - tags_to_remove + tags_to_add

    The derived source/target captions are also returned as STRINGs so you can
    inspect exactly what drove the edit.
    """

    @classmethod
    def INPUT_TYPES(cls):
        base = AnimaDirectEdit.INPUT_TYPES()
        req = base["required"]
        return {
            "required": {
                "model": req["model"],
                "clip": req["clip"],
                "vae": req["vae"],
                "image": req["image"],
                "max_megapixels": req["max_megapixels"],
                "tagger": (
                    "ANIMA_TAGGER",
                    {"tooltip": "AnimaTagger from the Anima Tagger Loader node."},
                ),
                "min_confidence": (
                    "FLOAT",
                    {
                        "default": 0.0,
                        "min": 0.0,
                        "max": 1.0,
                        "step": 0.05,
                        "tooltip": (
                            "Extra probability floor on the auto-tagged source "
                            "caption, on top of the tagger's own per-tag "
                            "thresholds. Only tags whose confidence is >= this "
                            "are kept. 0.0 = use the tagger's defaults; raise "
                            "(e.g. 0.4–0.6) to keep only confident tags."
                        ),
                    },
                ),
                "tags_to_add": (
                    "STRING",
                    {
                        "multiline": True,
                        "default": "",
                        "tooltip": (
                            "Comma-separated tags to ADD on top of the "
                            "auto-tagged source caption. These describe the "
                            "edit (e.g. 'smile, red dress'). Already-present "
                            "tags are skipped."
                        ),
                    },
                ),
                "tags_to_remove": (
                    "STRING",
                    {
                        "multiline": True,
                        "default": "",
                        "tooltip": (
                            "Optional comma-separated tags to REMOVE from the "
                            "auto-tagged source caption before adding "
                            "(case/underscore-insensitive). Leave empty to "
                            "only add."
                        ),
                    },
                ),
                "negative_prompt": req["negative_prompt"],
                "infer_steps": req["infer_steps"],
                "guidance_scale": req["guidance_scale"],
                "invert_guidance": req["invert_guidance"],
                "t_inj": req["t_inj"],
            },
        }

    RETURN_TYPES = ("LATENT", "STRING", "STRING")
    RETURN_NAMES = ("latent", "source_tag", "target_tag")
    FUNCTION = "edit_autotag"
    CATEGORY = "anima"
    DESCRIPTION = (
        "DirectEdit driven by a delta over an auto-derived caption. Tags the "
        "source image with the wired-in AnimaTagger to get psi_src, then "
        "applies your add/remove tag deltas to form psi_tar and runs the same "
        "invert + delta_z-anchored edit as Anima DirectEdit. Returns the "
        "edited LATENT plus the derived source/target captions."
    )

    def edit_autotag(
        self,
        model,
        clip,
        vae,
        image: torch.Tensor,
        max_megapixels: float,
        tagger,
        min_confidence: float,
        tags_to_add: str,
        tags_to_remove: str,
        negative_prompt: str,
        infer_steps: int,
        guidance_scale: float,
        invert_guidance: float,
        t_inj: int = 0,
    ):
        pil_src = _comfy_image_to_pil(image)
        psi_src = (
            tagger.predict_caption(pil_src, min_confidence=min_confidence) or ""
        ).strip()
        if not psi_src:
            raise ValueError(
                "AnimaDirectEditAutoTag: the tagger returned an empty caption "
                "for this image — cannot derive a source tag."
            )
        psi_tar = _merge_tags(psi_src, tags_to_add, tags_to_remove)

        (latent,) = AnimaDirectEdit().edit(
            model=model,
            clip=clip,
            vae=vae,
            image=image,
            source_tag=psi_src,
            target_tag=psi_tar,
            negative_prompt=negative_prompt,
            infer_steps=infer_steps,
            flow_shift=1.0,  # DirectEdit standard (Anima base-v1.0); invert/edit share it.
            guidance_scale=guidance_scale,
            invert_guidance=invert_guidance,
            max_megapixels=max_megapixels,
            t_inj=t_inj,
        )
        return (latent, psi_src, psi_tar)


NODE_CLASS_MAPPINGS = {
    "AnimaDirectEdit": AnimaDirectEdit,
    "AnimaDirectEditAutoTag": AnimaDirectEditAutoTag,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "AnimaDirectEdit": "Anima DirectEdit",
    "AnimaDirectEditAutoTag": "Anima DirectEdit (Auto-Tag Source)",
}
