network_type = "lokr"
network_dim = 16
network_alpha = 8
conv_dim = 1
conv_alpha = 4
lokr_factor = 8
decompose_both = true
use_tucker = true
scale_weight_norms = 1.0

learning_rate = 0.0002
lr_scheduler = "cosine"
max_train_epochs = 10
optimizer_type = "CAME_C"

gradient_checkpointing = false
gradient_checkpointing_last_n = 28
gradient_checkpointing_sac = true
torch_compile = true

output_name = "anima_lokr"
