"""Sync inference subsets of anima_lora into custom-node ``_vendor/`` trees.

Each ComfyUI node tries to import the live ``library.*`` first, falling back
to a bundled vendor copy when the host install isn't sitting inside the
anima_lora repo. This script keeps those vendor copies fresh.

Three targets:

* ``custom_nodes/comfyui-anima-tagger/_vendor/`` — captioning + PE encoder
  inference path (AnimaTagger, tag rules/groups, vision encoder, vendored PE).
* ``custom_nodes/comfyui-anima-directedit/_vendor/`` — directedit primitives,
  trimmed sampling helper, the trimmed ``CONSTANT_TOKEN_BUCKETS`` constant,
  and a tiny ``library.anima.models`` stub so the lazy ``Anima`` annotation
  resolves. DirectEdit no longer pulls in AnimaTagger / vision / edit
  dispatcher — its node consumes ``source_tag`` / ``target_tag`` STRINGs
  directly, with image-driven captioning handled externally by
  ``AnimaTaggerCaption``.
* ``custom_nodes/comfyui-hydralora/_vendor/`` — the pure-compute router
  kernels imported by ``adapter.py`` + ``fera.py`` (FEI 2-band / n-band,
  σ sinusoidal features, σ-band partition mask). ``library/inference/
  router_compute.py`` is the single import surface; it pulls
  ``library/runtime/fei.py`` and ``networks/lora_modules/router_state.py``
  transitively, so we vendor all three verbatim. Trained router weights are
  bit-sensitive to these kernels, so any drift between the live tree and
  vendored copy produces silently corrupted gates at inference.

Run before bumping a node version / publishing:

    python scripts/sync_vendor.py

The vendor tree mirrors the live namespace (``library.*`` / ``networks.*``)
so the copied files' internal imports keep working unchanged.
"""

from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TAGGER_VENDOR = ROOT / "custom_nodes" / "comfyui-anima-tagger" / "_vendor"
DIRECTEDIT_VENDOR = ROOT / "custom_nodes" / "comfyui-anima-directedit" / "_vendor"
HYDRALORA_VENDOR = ROOT / "custom_nodes" / "comfyui-hydralora" / "_vendor"

# ---------------------------------------------------------------------------
# Tagger-only captioning + vision subset. After the directedit node was
# refactored to take ``source_tag``/``target_tag`` STRINGs directly (no
# embedded tagger), this whole tree is only needed by the tagger vendor.
# ---------------------------------------------------------------------------

TAGGER_VERBATIM: list[tuple[str, str]] = [
    ("library/captioning/anima_tagger.py", "library/captioning/anima_tagger.py"),
    (
        "library/captioning/anima_tagger_model.py",
        "library/captioning/anima_tagger_model.py",
    ),
    ("library/captioning/tag_rules.py", "library/captioning/tag_rules.py"),
    ("library/captioning/tag_groups.py", "library/captioning/tag_groups.py"),
    ("library/vision/encoder.py", "library/vision/encoder.py"),
    ("library/vision/encoders.py", "library/vision/encoders.py"),
    ("library/vision/buckets.py", "library/vision/buckets.py"),
    ("library/models/pe.py", "library/models/pe.py"),
    (
        "networks/methods/ip_adapter_pe_lora.py",
        "networks/methods/ip_adapter_pe_lora.py",
    ),
]

TAGGER_PACKAGE_DIRS: list[str] = [
    "library",
    "library/captioning",
    "library/vision",
    "library/models",
    "library/datasets",
    "networks",
    "networks/methods",
]

TRIMMED_IMAGE_UTILS = '''"""Trimmed extract of library/datasets/image_utils.py for the vendored
inference path. Contains only ``IMAGE_TRANSFORMS`` — the [-1, 1] normalization
the AnimaTagger and PE pipelines apply post-resize.

DO NOT EDIT — regenerated by scripts/sync_vendor.py.
"""

from __future__ import annotations

from torchvision import transforms

IMAGE_TRANSFORMS = transforms.Compose(
    [
        transforms.ToTensor(),
        transforms.Normalize([0.5], [0.5]),
    ]
)
'''

TRIMMED_ANIMA_TAGGER_DATA = '''"""Trimmed extract of library/captioning/anima_tagger_data.py for the vendored
inference path. Contains only ``pil_resize_to_bucket`` — the LANCZOS pre-resize
to the encoder's nearest-aspect bucket. The full live module also exposes
training-only dataset / cache builders; those aren't needed at inference.

DO NOT EDIT — regenerated by scripts/sync_vendor.py.
"""

from __future__ import annotations

from PIL import Image

from library.vision.buckets import BucketSpec, bucket_pixel_size, pick_bucket


def pil_resize_to_bucket(img: Image.Image, spec: BucketSpec) -> Image.Image:
    """LANCZOS-resize a PIL image to its closest bucket size for ``spec``."""
    w, h = img.size
    h_p, w_p = pick_bucket(h, w, spec)
    target_h, target_w = bucket_pixel_size((h_p, w_p), spec)
    if (h, w) != (target_h, target_w):
        img = img.resize((target_w, target_h), Image.Resampling.LANCZOS)
    return img
'''

TAGGER_TRIMMED: list[tuple[str, str]] = [
    ("library/datasets/image_utils.py", TRIMMED_IMAGE_UTILS),
    ("library/captioning/anima_tagger_data.py", TRIMMED_ANIMA_TAGGER_DATA),
]

# ---------------------------------------------------------------------------
# DirectEdit vendor files.
# ---------------------------------------------------------------------------

DIRECTEDIT_VERBATIM: list[tuple[str, str]] = [
    ("library/inference/directedit.py", "library/inference/directedit.py"),
    (
        "library/inference/directedit_splice.py",
        "library/inference/directedit_splice.py",
    ),
]

DIRECTEDIT_PACKAGE_DIRS: list[str] = [
    "library",
    "library/inference",
    "library/anima",
    "library/datasets",
]

# Trimmed extract: only ``get_timesteps_sigmas`` from the full sampling
# module. Drops the diffusers dependency the rest of the file pulls in.
TRIMMED_SAMPLING = '''"""Trimmed extract of library/inference/sampling.py for the vendored
DirectEdit path. Contains only ``get_timesteps_sigmas`` — the only helper
the DirectEdit ComfyUI node calls. Drops the diffusers-based samplers the
full module exposes (not needed at inference here).

DO NOT EDIT — regenerated by scripts/sync_vendor.py.
"""

from __future__ import annotations

from typing import Tuple

import torch


def get_timesteps_sigmas(
    sampling_steps: int, shift: float, device: torch.device
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Generate flow-matching timesteps + sigmas for ``sampling_steps`` Euler steps."""
    sigmas = torch.linspace(1, 0, sampling_steps + 1)
    sigmas = (shift * sigmas) / (1 + (shift - 1) * sigmas)
    sigmas = sigmas.to(torch.float32)
    timesteps = (sigmas[:-1] * 1000).to(dtype=torch.float32, device=device)
    return timesteps, sigmas
'''

# Trimmed extract: only the ``CONSTANT_TOKEN_BUCKETS`` constant. Full file
# pulls in cv2, numpy bucket-manager classes, etc.
TRIMMED_BUCKETS = '''"""Trimmed extract of library/datasets/buckets.py for the vendored
DirectEdit path. Contains only ``CONSTANT_TOKEN_BUCKETS`` — the bucket-size
table the DirectEdit ComfyUI node consults to pick a target resolution.

DO NOT EDIT — regenerated by scripts/sync_vendor.py.
"""

from __future__ import annotations

# (W, H) buckets — kept in lockstep with the live library/datasets/buckets.py
# table. If you change the live constant, re-run scripts/sync_vendor.py to
# refresh this file.
CONSTANT_TOKEN_BUCKETS = {{CONSTANT_TOKEN_BUCKETS_LITERAL}}
'''

STUB_ANIMA_MODELS = '''"""Stub of library.anima.models for the vendored DirectEdit path.

The live module is ~2.4k LOC and defines the full Anima DiT. The vendored
``library/inference/directedit.py`` imports it solely for a type annotation
that is already lazy (``from __future__ import annotations``), so a tiny
placeholder class is enough to keep the import succeeding. The actual model
passed at runtime is whatever the ComfyUI MODEL socket carries.

DO NOT EDIT — regenerated by scripts/sync_vendor.py.
"""

from __future__ import annotations


class Anima:
    """Placeholder type. The live class lives in the parent anima_lora repo."""
'''


def _read_constant_token_buckets_literal() -> str:
    """Pull the live ``CONSTANT_TOKEN_BUCKETS`` source slice so the trimmed
    file mirrors the canonical table exactly. Avoids hand-syncing two copies
    of the bucket list."""
    src = (ROOT / "library" / "datasets" / "buckets.py").read_text()
    marker = "CONSTANT_TOKEN_BUCKETS = "
    start = src.index(marker) + len(marker)
    # The literal is a Python list spanning multiple lines until the matching
    # ``]`` at column 0.
    end = src.index("\n]\n", start) + 2
    return src[start:end]


DIRECTEDIT_TRIMMED_TEMPLATES: list[tuple[str, str]] = [
    ("library/inference/sampling.py", TRIMMED_SAMPLING),
    ("library/datasets/buckets.py", TRIMMED_BUCKETS),
    ("library/anima/models.py", STUB_ANIMA_MODELS),
]


# ---------------------------------------------------------------------------
# Generic build helpers.
# ---------------------------------------------------------------------------


def _write_pkg_markers(vendor_root: Path, package_dirs: list[str]) -> None:
    for d in package_dirs:
        pkg = vendor_root / d
        pkg.mkdir(parents=True, exist_ok=True)
        (pkg / "__init__.py").write_text("")


def _copy_verbatim(vendor_root: Path, files: list[tuple[str, str]]) -> None:
    for src_rel, dst_rel in files:
        src = ROOT / src_rel
        dst = vendor_root / dst_rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        print(f"  copied  {src_rel}")


def _write_trimmed(vendor_root: Path, files: list[tuple[str, str]]) -> None:
    for dst_rel, content in files:
        dst = vendor_root / dst_rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(content)
        print(f"  trimmed {dst_rel}")


def _resolve_directedit_trimmed() -> list[tuple[str, str]]:
    """Substitute live constants into trimmed templates."""
    out: list[tuple[str, str]] = []
    bucket_literal = _read_constant_token_buckets_literal()
    for dst_rel, template in DIRECTEDIT_TRIMMED_TEMPLATES:
        content = template.replace("{{CONSTANT_TOKEN_BUCKETS_LITERAL}}", bucket_literal)
        out.append((dst_rel, content))
    return out


def build_tagger_vendor() -> None:
    print(f"\n[tagger] -> {TAGGER_VENDOR.relative_to(ROOT)}")
    if TAGGER_VENDOR.exists():
        shutil.rmtree(TAGGER_VENDOR)
    TAGGER_VENDOR.mkdir(parents=True)
    (TAGGER_VENDOR / "__init__.py").write_text(
        '"""Bundled inference subset of anima_lora.\n\n'
        "Synced by scripts/sync_vendor.py — do not edit by hand.\n"
        '"""\n'
    )
    _write_pkg_markers(TAGGER_VENDOR, TAGGER_PACKAGE_DIRS)
    _copy_verbatim(TAGGER_VENDOR, TAGGER_VERBATIM)
    _write_trimmed(TAGGER_VENDOR, TAGGER_TRIMMED)


def build_directedit_vendor() -> None:
    print(f"\n[directedit] -> {DIRECTEDIT_VENDOR.relative_to(ROOT)}")
    if DIRECTEDIT_VENDOR.exists():
        shutil.rmtree(DIRECTEDIT_VENDOR)
    DIRECTEDIT_VENDOR.mkdir(parents=True)
    (DIRECTEDIT_VENDOR / "__init__.py").write_text(
        '"""Bundled inference subset of anima_lora.\n\n'
        "Synced by scripts/sync_vendor.py — do not edit by hand.\n"
        '"""\n'
    )
    _write_pkg_markers(DIRECTEDIT_VENDOR, DIRECTEDIT_PACKAGE_DIRS)
    _copy_verbatim(DIRECTEDIT_VENDOR, DIRECTEDIT_VERBATIM)
    _write_trimmed(DIRECTEDIT_VENDOR, _resolve_directedit_trimmed())


# ---------------------------------------------------------------------------
# Hydralora vendor tree — the pure-compute kernels imported by
# adapter.py + fera.py via the live-or-vendor resolver in adapter.py.
# router_compute.py is the single import surface; it pulls in fei.py and
# router_state.py transitively, so we vendor all three verbatim.
# ---------------------------------------------------------------------------

HYDRALORA_VERBATIM: list[tuple[str, str]] = [
    ("library/inference/router_compute.py", "library/inference/router_compute.py"),
    ("library/runtime/fei.py", "library/runtime/fei.py"),
    ("networks/lora_modules/router_state.py", "networks/lora_modules/router_state.py"),
]

HYDRALORA_PACKAGE_DIRS: list[str] = [
    "library",
    "library/inference",
    "library/runtime",
    "networks",
    "networks/lora_modules",
]


def build_hydralora_vendor() -> None:
    print(f"\n[hydralora] -> {HYDRALORA_VENDOR.relative_to(ROOT)}")
    if HYDRALORA_VENDOR.exists():
        shutil.rmtree(HYDRALORA_VENDOR)
    HYDRALORA_VENDOR.mkdir(parents=True)
    (HYDRALORA_VENDOR / "__init__.py").write_text(
        '"""Bundled inference subset of anima_lora.\n\n'
        "Synced by scripts/sync_vendor.py — do not edit by hand.\n"
        '"""\n'
    )
    _write_pkg_markers(HYDRALORA_VENDOR, HYDRALORA_PACKAGE_DIRS)
    _copy_verbatim(HYDRALORA_VENDOR, HYDRALORA_VERBATIM)


def main() -> None:
    build_tagger_vendor()
    build_directedit_vendor()
    build_hydralora_vendor()
    print("\nvendor trees fresh.")


if __name__ == "__main__":
    main()
