"""Anima Tagger ComfyUI nodes.

Two nodes:

* ``AnimaTaggerLoader`` - load an ``AnimaTagger`` checkpoint from disk and
  emit a reusable ``ANIMA_TAGGER`` socket. ComfyUI memoizes loader outputs
  by inputs, so the tagger persists across graph runs without per-call
  reload.
* ``AnimaTaggerCaption`` - take an ``ANIMA_TAGGER`` and an ``IMAGE`` and
  return the predicted caption as a ``STRING``. Useful outside DirectEdit
  (e.g., feeding any sampler's text input or pre-filling LoRA captions).

The ``ANIMA_TAGGER`` socket type is a plain string in ComfyUI's type
system, so the AnimaDirectEdit node in ``comfyui-anima-directedit`` consumes
the same socket without a code-level dependency on this package.
"""

from __future__ import annotations

import importlib
import json
import logging
import shutil
import sys
from pathlib import Path

import numpy as np
import torch

# Resolve where to import ``library.captioning.anima_tagger`` from.
#
# Two install shapes are supported:
#
# 1. **Inside the anima_lora repo** (dev / monorepo install). This file lives
#    at ``anima_lora/custom_nodes/comfyui-anima-tagger/nodes.py`` so
#    ``parents[2]`` is the repo root, and the live ``library/`` is reachable.
# 2. **Standalone ComfyUI install** (just dropped this folder into
#    ``ComfyUI/custom_nodes/``). Then ``parents[2]`` is ``ComfyUI/custom_nodes/``
#    which has no ``library/`` - fall back to the bundled inference subset
#    under ``_vendor/``. The vendor tree is generated by
#    ``scripts/sync_tagger_vendor.py`` in the parent repo and ships with the
#    published node version.
HERE = Path(__file__).resolve().parent
ANIMA_LORA = HERE.parents[1]
VENDOR = HERE / "_vendor"

# HF repo we auto-fetch the tagger checkpoint from when ``tagger_dir`` is
# missing required files. Mirrors the PE-Core auto-fetch already in this
# loader - the user gets a working node out of the box without manual
# downloads, while still being able to point ``tagger_dir`` at a
# custom-trained checkpoint.
_HF_TAGGER_REPO = "sorryhyun/anima-tagger"
_REQUIRED_FILES = ("config.json", "model.safetensors", "vocab.json", "rules.yaml")
_OPTIONAL_FILES = ("thresholds.safetensors", "groups.yaml")

# The tagger is dual-encoder only (PE-Core + PE-Spatial, hard-routed). The
# pre-dual single-encoder ``v1`` checkpoint no longer loads. The dual-encoder
# checkpoint now lives at the repo root of ``sorryhyun/anima-tagger`` (it used
# to sit under a ``v2/`` subfolder), so no subfolder prefix is needed.
_HF_SUBFOLDER = ""
_DEFAULT_TAGGER_DIR = "models/captioners/anima-tagger-v2"

# Default vision-encoder checkpoints (auto-fetched if absent). Listed as the
# first dropdown row so a fresh install resolves to the auto-download target
# even before any ``.pt`` exists on disk.
_DEFAULT_PE_CKPT = "models/pe/PE-Core-L14-336.pt"
_DEFAULT_PE_AUX_CKPT = "models/pe/PE-Spatial-B16-512.pt"


def _list_tagger_dirs() -> list[str]:
    """Loadable tagger-checkpoint directories under ``models/captioners/``.

    A directory qualifies only when its ``config.json`` carries an
    ``aux_encoder`` field — i.e. it's a dual-encoder (PE-Core + PE-Spatial)
    checkpoint, the only architecture that still loads. Pre-dual / v1
    single-encoder dirs are skipped so the dropdown never offers a checkpoint
    that ``AnimaTagger`` would reject at load time. Returned as paths relative
    to ``ANIMA_LORA`` so the load() resolver (which prepends ``ANIMA_LORA`` for
    non-absolute inputs) accepts them unchanged. Empty when running standalone
    — the caller seeds the default dir so the dropdown is never empty and
    auto-fetch still works.
    """
    if not ANIMA_LORA.exists():
        return []
    base = ANIMA_LORA / "models" / "captioners"
    if not base.is_dir():
        return []
    out: list[str] = []
    for p in sorted(base.iterdir()):
        cfg = p / "config.json"
        if not cfg.exists():
            continue
        try:
            with open(cfg) as f:
                if not json.load(f).get("aux_encoder"):
                    continue
        except (OSError, ValueError):
            continue
        out.append(str(p.relative_to(ANIMA_LORA)))
    return out


def _list_pe_ckpts() -> list[str]:
    """Vision-encoder ``.pt`` checkpoints under ``models/pe/``, repo-relative.

    Empty when standalone — the caller seeds the canonical default so the
    dropdown is never empty and the auto-download target stays selectable.
    """
    if not ANIMA_LORA.exists():
        return []
    base = ANIMA_LORA / "models" / "pe"
    if not base.is_dir():
        return []
    return [str(p.relative_to(ANIMA_LORA)) for p in sorted(base.glob("*.pt"))]


def _dropdown(default: str, found: list[str]) -> list[str]:
    """Build a dropdown list with ``default`` pinned first, deduped.

    The default sits at the head even when absent from ``found`` (e.g. nothing
    downloaded yet) so it stays selectable as the auto-fetch target.
    """
    return [default] + [p for p in found if p != default]


def _ensure_tagger_dir(tdir: Path, hf_subfolder: str = "") -> None:
    """If ``tdir`` is missing any required tagger file, fetch the whole
    checkpoint from ``sorryhyun/anima-tagger`` into it.

    ``hf_subfolder`` (e.g. ``"v2"``) prefixes the repo path so different
    versions can be pulled from the same repo; downloaded files are flattened
    into ``tdir`` regardless of the source layout so the loader's directory
    contract (``tdir/config.json`` etc.) stays uniform across versions.

    Optional files (``thresholds.safetensors``, ``groups.yaml``) are
    best-effort - a 404 on the repo just means the published checkpoint
    doesn't ship that file. The required-file gate already guarantees the
    tagger can load.
    """
    if all((tdir / f).exists() for f in _REQUIRED_FILES):
        return
    from huggingface_hub import hf_hub_download
    from huggingface_hub.utils import EntryNotFoundError

    logger.info(
        "AnimaTaggerLoader: %s is missing required files - fetching %s%s (one-time).",
        tdir,
        _HF_TAGGER_REPO,
        f"/{hf_subfolder}" if hf_subfolder else "",
    )
    tdir.mkdir(parents=True, exist_ok=True)

    def _fetch_flat(fname: str) -> Path:
        repo_path = f"{hf_subfolder}/{fname}" if hf_subfolder else fname
        downloaded = Path(
            hf_hub_download(
                repo_id=_HF_TAGGER_REPO,
                filename=repo_path,
                local_dir=str(tdir),
            )
        )
        dest = tdir / fname
        if downloaded.resolve() != dest.resolve():
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(downloaded), str(dest))
        return dest

    for fname in _REQUIRED_FILES:
        _fetch_flat(fname)
    for fname in _OPTIONAL_FILES:
        try:
            _fetch_flat(fname)
        except EntryNotFoundError:
            logger.debug(
                "optional file %s not present on %s%s",
                fname,
                _HF_TAGGER_REPO,
                f"/{hf_subfolder}" if hf_subfolder else "",
            )


def _resolve_anima_tagger():
    """Return the ``AnimaTagger`` class from the live tree if reachable,
    else from the bundled vendor copy. Vendor wins only when the live import
    fails - keeps in-repo edits picked up automatically during development."""
    if str(ANIMA_LORA) not in sys.path:
        sys.path.insert(0, str(ANIMA_LORA))
    try:
        return importlib.import_module("library.captioning.anima_tagger").AnimaTagger
    except ImportError:
        if not VENDOR.exists():
            raise
        if str(VENDOR) not in sys.path:
            sys.path.insert(0, str(VENDOR))
        return importlib.import_module("library.captioning.anima_tagger").AnimaTagger


from PIL import Image  # noqa: E402

import comfy.model_management  # noqa: E402  ComfyUI module; only resolvable inside ComfyUI

AnimaTagger = _resolve_anima_tagger()  # noqa: E402

logger = logging.getLogger(__name__)


def _comfy_image_to_pil(image_tensor: torch.Tensor) -> Image.Image:
    """ComfyUI IMAGE [B, H, W, C] in [0,1] -> PIL.RGB (first batch element)."""
    arr = image_tensor[0].clamp(0, 1).cpu().numpy()
    return Image.fromarray((arr * 255).astype(np.uint8)).convert("RGB")


class AnimaTaggerLoader:
    """Load an AnimaTagger checkpoint as a reusable graph asset.

    ComfyUI memoizes loader outputs by inputs, so the tagger persists across
    invocations as long as ``tagger_dir`` doesn't change - no per-call
    reload from disk.
    """

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "tagger_dir": (
                    _dropdown(_DEFAULT_TAGGER_DIR, _list_tagger_dirs()),
                    {
                        "tooltip": (
                            "AnimaTagger checkpoint directory, picked from "
                            "the checkpoints discovered under "
                            "models/captioners/ (any dir with a config.json). "
                            "The first row is the default dual-encoder "
                            "checkpoint; if it's missing required files it's "
                            f"auto-fetched from {_HF_TAGGER_REPO} on first use."
                        ),
                    },
                ),
                "pe_ckpt": (
                    _dropdown(_DEFAULT_PE_CKPT, _list_pe_ckpts()),
                    {
                        "tooltip": (
                            "PE-Core-L14-336 vision-encoder checkpoint (.pt), "
                            "picked from models/pe/. Drives rating / "
                            "people-count / identity tags. If the default is "
                            "missing it's auto-fetched from "
                            "facebook/PE-Core-L14-336 on first use (one-time "
                            "~1 GB download)."
                        ),
                    },
                ),
                "pe_aux_ckpt": (
                    _dropdown(_DEFAULT_PE_AUX_CKPT, _list_pe_ckpts()),
                    {
                        "tooltip": (
                            "Auxiliary PE-Spatial-B16-512 vision-encoder "
                            "checkpoint (.pt), picked from models/pe/. Drives "
                            "localized tags in the dual-encoder tagger. If the "
                            "default is missing it's auto-fetched from "
                            "facebook/PE-Spatial-B16-512 on first use."
                        ),
                    },
                ),
            },
        }

    RETURN_TYPES = ("ANIMA_TAGGER",)
    RETURN_NAMES = ("tagger",)
    FUNCTION = "load"
    CATEGORY = "anima"
    DESCRIPTION = (
        "Load an AnimaTagger checkpoint. Output socket is consumed by "
        "AnimaTaggerCaption (image -> caption) and AnimaDirectEdit. ComfyUI "
        "memoizes the output, so re-running the graph reuses the same "
        "instance without reloading. Both the tagger checkpoint "
        f"({_HF_TAGGER_REPO}) and the PE-Core-L14-336 vision encoder are "
        "auto-downloaded if their paths don't exist yet."
    )

    def load(
        self,
        tagger_dir: str,
        pe_ckpt: str,
        pe_aux_ckpt: str = "",
    ):
        tdir = Path(tagger_dir.strip())
        if not tdir.is_absolute():
            tdir = ANIMA_LORA / tdir
        pe_path = Path(pe_ckpt)
        if not pe_path.is_absolute():
            pe_path = ANIMA_LORA / pe_path
        # Aux PE path is optional — empty string keeps the AnimaTagger
        # constructor default (None → encoder registry default → HF fallback).
        pe_aux_resolved: Path | None = None
        pe_aux_str = pe_aux_ckpt.strip() if pe_aux_ckpt else ""
        if pe_aux_str:
            pe_aux_resolved = Path(pe_aux_str)
            if not pe_aux_resolved.is_absolute():
                pe_aux_resolved = ANIMA_LORA / pe_aux_resolved
        # The only loadable architecture is the dual-encoder checkpoint, now at
        # the root of the HF repo (_HF_SUBFOLDER == "").
        _ensure_tagger_dir(tdir, hf_subfolder=_HF_SUBFOLDER)
        device = comfy.model_management.get_torch_device()
        logger.info(
            "AnimaTaggerLoader: loading %s on %s (pe=%s, pe_aux=%s)",
            tdir,
            device,
            pe_path,
            pe_aux_resolved if pe_aux_resolved else "<registry default>",
        )
        tagger = AnimaTagger(
            ckpt_dir=tdir,
            device=device,
            pe_ckpt=pe_path,
            pe_aux_ckpt=pe_aux_resolved,
        )
        return (tagger,)


class AnimaTaggerCaption:
    """Run an AnimaTagger over an image and emit the caption as a STRING."""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "tagger": (
                    "ANIMA_TAGGER",
                    {"tooltip": "AnimaTagger from AnimaTaggerLoader."},
                ),
                "image": ("IMAGE",),
            },
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("caption",)
    FUNCTION = "caption"
    CATEGORY = "anima"
    DESCRIPTION = (
        "Predict an Anima-formatted caption for an image using AnimaTagger. "
        "Output is a comma-separated tag string in Anima's canonical slot "
        "order (rating, count, characters, copyrights, @artists, generals) "
        "with underscores replaced by spaces - drop-in for any STRING input "
        "(CLIPTextEncode, prompt_src_override on AnimaDirectEdit, etc.)."
    )

    def caption(self, tagger: AnimaTagger, image: torch.Tensor):
        pil = _comfy_image_to_pil(image)
        text = tagger.predict_caption(pil)
        logger.info("AnimaTaggerCaption: %r", text)
        return (text,)


NODE_CLASS_MAPPINGS = {
    "AnimaTaggerLoader": AnimaTaggerLoader,
    "AnimaTaggerCaption": AnimaTaggerCaption,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "AnimaTaggerLoader": "Anima Tagger Loader",
    "AnimaTaggerCaption": "Anima Tagger Caption",
}
